#!/usr/bin/env python3
"""Send the weekly team summary email via Microsoft Graph API (Mail.Send).

Usage:
    python3 send_email.py --to evan.groenke@amd.com --subject "..." --body-file email.html
    python3 send_email.py --to evan.groenke@amd.com --subject "..." --body "plain text"
"""
import argparse
import json
import ssl
import sys
import urllib.parse
import urllib.request
from pathlib import Path

TOKEN_FILE = Path.home() / ".config" / "microsoft-graph" / "token.json"
GRAPH_BASE = "https://graph.microsoft.com/v1.0"


def get_token() -> str:
    data = json.loads(TOKEN_FILE.read_text())
    import time
    if data.get("expires_at", 0) - time.time() < 300 and data.get("refresh_token"):
        return _refresh(data)
    return data.get("access_token", "")


def _refresh(data: dict) -> str:
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    opener = urllib.request.build_opener(urllib.request.HTTPSHandler(context=ctx))
    payload = urllib.parse.urlencode({
        "client_id": data["client_id"],
        "grant_type": "refresh_token",
        "refresh_token": data["refresh_token"],
        "scope": data.get("scopes", "Mail.Send offline_access"),
    }).encode()
    req = urllib.request.Request(
        f"https://login.microsoftonline.com/{data['tenant_id']}/oauth2/v2.0/token",
        data=payload,
    )
    result = json.loads(opener.open(req, timeout=15).read())
    import time
    data["access_token"] = result["access_token"]
    data["expires_at"] = time.time() + result.get("expires_in", 3600)
    TOKEN_FILE.write_text(json.dumps(data, indent=2))
    return result["access_token"]


def send_email(to: str, subject: str, body: str, html: bool = True) -> bool:
    token = get_token()
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    opener = urllib.request.build_opener(urllib.request.HTTPSHandler(context=ctx))

    message = {
        "message": {
            "subject": subject,
            "body": {
                "contentType": "HTML" if html else "Text",
                "content": body,
            },
            "toRecipients": [{"emailAddress": {"address": to}}],
        },
        "saveToSentItems": True,
    }

    data = json.dumps(message).encode()
    req = urllib.request.Request(
        f"{GRAPH_BASE}/me/sendMail",
        data=data,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        opener.open(req, timeout=30)
        print(f"Email sent to {to}: {subject}")
        return True
    except urllib.error.HTTPError as e:
        print(f"Email send failed: {e.code} {e.read().decode()}", file=sys.stderr)
        return False


def markdown_to_html(text: str) -> str:
    """Minimal markdown-to-HTML for the email body."""
    lines = text.split("\n")
    html_lines = []
    for line in lines:
        if line.startswith("# "):
            html_lines.append(f"<h2>{line[2:]}</h2>")
        elif line.startswith("## "):
            html_lines.append(f"<h3>{line[3:]}</h3>")
        elif line.startswith("### "):
            html_lines.append(f"<h4>{line[4:]}</h4>")
        elif line.startswith("• ") or line.startswith("- "):
            html_lines.append(f"<li>{line[2:]}</li>")
        elif line.startswith("**") and line.endswith("**"):
            html_lines.append(f"<b>{line[2:-2]}</b><br>")
        elif line.strip() == "":
            html_lines.append("<br>")
        else:
            html_lines.append(f"{line}<br>")

    body = "\n".join(html_lines)
    return f"""<html><body style="font-family: Calibri, Arial, sans-serif; font-size: 14px; color: #1a1a1a;">
{body}
<br><hr style="border:none;border-top:1px solid #ddd;">
<p style="color:#888;font-size:12px;">Generated by weekly-tracker — AMD DCGPU TME Team</p>
</body></html>"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--to", required=True)
    parser.add_argument("--subject", required=True)
    parser.add_argument("--body", default="")
    parser.add_argument("--body-file", default="")
    parser.add_argument("--plain", action="store_true")
    args = parser.parse_args()

    if args.body_file:
        body = Path(args.body_file).read_text()
    else:
        body = args.body

    if not args.plain:
        body = markdown_to_html(body)

    success = send_email(args.to, args.subject, body, html=not args.plain)
    sys.exit(0 if success else 1)
